### ISSUE TITLE
Include directory is not specified in CMakeLists.txt

### ISSUE THREAD

**Issue by rpbostock** [planed-es/csvpp#1]
It would be really useful to include the following line in CMakeLists.txt so that we can pull this project in using FetchContent:
`target_include_directories(csvpp PUBLIC src)`

**Comment by delipl** [comment]
Hi!
I'm also trying to FetchContent and I'm adding this line:
```cmake
target_link_libraries(csvpp Boost::filesystem Boost::system)
```

**Comment by rpbostock** [comment]
This is what I've used so far and works well for me (on Linux, but apparently won't work on Windows - remove .txt extensions). 
- Applies the patch and checks to see whether it has been applied before or not.
- Includes the headers as required
- Switching from a shared library to a static library to make it easier to include in final binaries without dependencies.
- I had a particular need to use a specific BOOST version, but that won't probably be needed for others

[csvpp.cmake.txt](https://github.com/Plaristote/csvpp/files/8706208/csvpp.cmake.txt)
[0001-csvpp-include.patch.txt](https://github.com/Plaristote/csvpp/files/8706209/0001-csvpp-include.patch.txt)

**Comment by Plaristote** [comment]
Hi ! Sorry for the delay ! I wasn't aware of the FetchContent feature. I moved on to build2 when it comes to distributing dependencies (mandatory advertising for an under-appreciated build tool), but this is an interesting novelty.

Commit ae26f8e should fix the issue.

I also added a csvpp_static target in 9fd291f.
